server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /auth {
        proxy_pass http://incident-manager:8080;
    }

    location /devices {
        proxy_pass http://incident-manager:8080;
    }

    location /incidents {
        proxy_pass http://incident-manager:8080;
    }
}