spring:
  application:
    name: incident-manager
  datasource:
    url: jdbc:postgresql://localhost:5440/incident_manager
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
