spring:
  application:
    name: incident-manager
  datasource:
    url: jdbc:postgresql://localhost:5440/incident_manager
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

app:
  kafka:
    incidents-topic: incidents
